include_home_segment: true
home_segment_title: Home
include_title_segment: false
language_path_prefix_as_segment: false
use_menu_title_as_fallback: true
remove_repeated_segments: true
_core:
  default_config_hash: MymgTM4i959vZLJ3F-hpn_ntX-johso5eQqRm-03r0Y
include_invalid_paths: false
excluded_paths: ''
segments_separator: null
title_segment_as_link: false
title_from_page_when_available: false
replaced_titles: ''
home_segment_keep: 0
absolute_paths: false
