smtp_on: true
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: tamba.s.lamin@lamtech.sl
smtp_password: MotherSIA@2012
smtp_from: tamba.s.lamin@lamtech.sl
smtp_fromname: 'Sierra Leone Open Elections Data Platform'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
